---
- name: Stop nginx
  service:
    name: nginx
    state: stopped

- name: Install prerequisites
  apt:
    name:
      - software-properties-common
    state: present

- name: Add OpenResty GPG key
  apt_key:
    url: "https://openresty.org/package/pubkey.gpg"
    state: present

- name: Add OpenResty repository
  apt_repository:
    repo: "deb http://openresty.org/package/ubuntu {{ ansible_lsb.codename }} main"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install OpenResty
  apt:
    name: openresty
    state: present

- name: Start and enable OpenResty service
  systemd:
    name: openresty
    state: started
    enabled: yes

- name: Copy nginx config
  copy:
    remote_src: true
    src: /etc/nginx/nginx.conf
    dest: /etc/openresty/nginx.conf
    mode: 0644

- name: "Comment out pid"
  replace:
    path: /etc/openresty/nginx.conf
    regexp: '^(pid .*)'
    replace: '#\1'

- name: "Don't import modules"
  replace:
    path: /etc/openresty/nginx.conf
    regexp: '^(include /etc/nginx/modules-enabled/\*.conf;)'
    replace: '#\1'

- name: Remove default root
  replace:
    path: /etc/nginx/conf.d/ssl_main.conf
    regexp: 'root /var/www/html;'
    replace: ''

- name: Remove default index
  replace:
    path: /etc/nginx/conf.d/ssl_main.conf
    regexp: 'index index.html index.htm;'
    replace: ''

- name: Make sure nginx is enabled
  service:
    name: openresty
    enabled: yes

- name: Make sure nginx is started
  service:
    name: openresty
    state: started
  register: openresty_service_started

- name: Reload nginx
  service:
    name: openresty
    state: reloaded